#!/usr/bin/env bash
# Renders the vaqum Homebrew formula for one release, to stdout.
#
# Usage: render.sh <version> <sha256-x86_64-darwin> <sha256-aarch64-darwin> <sha256-x86_64-linux>
#
# Used by .github/workflows/release.yml's homebrew-tap job; run it by hand
# to preview a formula before the tap repo/token are set up (see README.md
# in this directory).

set -euo pipefail

if [ "$#" -ne 4 ]; then
  echo "usage: $0 <version> <sha256-intel> <sha256-arm> <sha256-linux>" >&2
  exit 1
fi

version="$1"
sha_intel="$2"
sha_arm="$3"
sha_linux="$4"

cat <<EOF
# Auto-generated by packaging/homebrew/render.sh — do not edit by hand.
class Vaqum < Formula
  desc "Losslessly compress, decompress, and securely shred files"
  homepage "https://github.com/marcdomain/vaqum"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/marcdomain/vaqum/releases/download/v${version}/vaqum-${version}-aarch64-apple-darwin.tar.gz"
      sha256 "${sha_arm}"
    end
    on_intel do
      url "https://github.com/marcdomain/vaqum/releases/download/v${version}/vaqum-${version}-x86_64-apple-darwin.tar.gz"
      sha256 "${sha_intel}"
    end
  end

  on_linux do
    url "https://github.com/marcdomain/vaqum/releases/download/v${version}/vaqum-${version}-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "${sha_linux}"
  end

  def install
    bin.install "vaqum"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/vaqum --version")
  end
end
EOF
